version: '3.0'

services:
  main:
    container_name: mainprof
    build: 
      context: .
      dockerfile: ./dockerfile
    env_file:
    - .development.env
    volumes:
      - .:/app
      - /app
    ports:
    - 9000:9000
    - 9228:9229
    command:  npm run start:dev
    depends_on:
    - postgres  
    - listener
    restart: always
  
  listener:
    build: .
    image: app
    command: npm run listen
    volumes:
      - .:/app
      - /app
    ports:
    - 5679:5672
    depends_on:
      - postgres 
    restart: always

  postgres:
    container_name: postgresprof
    image: postgres:12
    env_file:
      - .development.env
    volumes:
      - pg_data:/var/lib/postgresql/data/pg_data
    environment:
      PGDATA: /var/lib/postgresql/data/pg_data
    ports:
    - 5438:5432
    restart: always
volumes:
  pg_data:   